### PR TITLE
Fixed crash due to inverted logic check for an exception

### PR DESCRIPTION
**Pull request by CliffCawley**
Not sure if this is related to the other one I found, but looks like you just messed up logic, because you access e in the else, not the if

### CODE REVIEW

**Comment by CliffCawley** [comment]
Added another inverted logic check bug here which resulted in a null exception

**Comment by CliffCawley** [comment]
Found another inverted logic check!

**Comment by TorbenK** [comment]
I will had the fix manually as this references the Development-2.0 branch.

**Comment by CliffCawley** [comment]
Ah yup, this was my first PR so I wasn't sure what I was doing :)

**Comment by TorbenK** [comment]
Added manually. Thank you very much, you are added as contributor on the readme

**Pull request closed without merging**
