### PR TITLE
Update iOS TKCustomMapRenderer.cs

### PR DESCRIPTION
**Pull request by JeanCollas**
UpdateMapRegion() fails when MapRegion is null at startup

### CODE REVIEW

**Comment by TorbenK** [comment]
I think the root is the same problem which is documented in this pull request: #41

**Comment by JeanCollas** [comment]
I don't think so, a null exception happened when I was on the map, doing nothing else than clicking...

**Comment by TorbenK** [comment]
Did this only happen on iOS?

**Comment by JeanCollas** [comment]
Yes, and I have no idea how I got that (just tapped several times the map, maybe while reloading the pins, i don't remember), but it killed the app, so probably better to avoid it!

**Comment by TorbenK** [comment]
Added to dev and closed

**Pull request closed without merging**
