### PR TITLE
286-NullPointerException both Android and iOS

### PR DESCRIPTION
**Pull request by tuyen-vuduc**
Fix NullPointerException while selecting a callout on Android and iOS.

### CODE REVIEW

**Comment by tuyen-vuduc** [comment]
@TorbenK Are you actively maintaining this project?

I saw that the CI is failed due to UWP project. 
Is that ok to remove that project, at least from the solution?

Regards,
Tuyen

**Comment by TorbenK** [comment]
Thanks for the PR! Don't worry about the failed build, I will merge and fix the build asap.

**Comment by nbsoftware** [comment]
Hi Torben, do you know when you'll be able to integrate this PR?
I too have NullPointerException on CalloutClicked with release 2.0.0
Thanks

**Comment by tuyen-vuduc** [comment]
@nbsoftware In the meanwhile, you could try to install the package from our myget
```
https://www.myget.org/F/naxam/api/v3/index.json
```

**Comment by nbsoftware** [comment]
Thanks @tuyen-vuduc !
I'll give it a try.

**Comment by thomasgalliker** [comment]
I tried to use TK.CustomMap, but the Android sample crashes with Null Reference Exception at startup time. Would be nice if someone could merge this PR.

**Comment by ernestochaves** [comment]
Does anyone know if this is still active, maintained?

**Comment by tuyen-vuduc** [comment]
@ernestochaves I think the community should contribute :). 

If you guys don't mind, just create PR to my forked repo (Naxam/TK.CustomMap), then I will help to create nuget package and publish to `https://www.myget.org/F/naxam/api/v3/index.json`

In the meanwhile, this PR is already published to that feed, @thomasgalliker.

Cheers.

**Comment by ernestochaves** [comment]
Your PR makes it possible to run the project for me, as I needed some sample code to get started. Thanks. 
I still don't know enough to contribute to this project. But if we are going to use it, I believe is not an unreasonable question to ask if it is still maintained. No offense intended or anything.

**Pull request merged**
