### PR TITLE
#27 - Fixed NullReference exception when access null Map and FormsMap

### PR DESCRIPTION
**Pull request by CliffCawley**

### CODE REVIEW

**Comment by TorbenK** [comment]
I will had the fix manually as this references the master branch.

**Comment by CliffCawley** [comment]
@TorbenK I had to add some more null references you should take across :)

**Comment by CliffCawley** [comment]
(Which branch should I use so you don't have to do this manually?)

**Comment by TorbenK** [comment]
Development

**Comment by TorbenK** [comment]
Added manually. Thank you very much, you are added as contributor on the readme

**Pull request closed without merging**
