### PR TITLE
Add Fields (Address, PhoneNumber, Website) to TkPlaceDetails class and retrieve the data from the API

### PR DESCRIPTION
**Pull request by Spierki**

### CODE REVIEW

**Comment by TorbenK** [comment]
Please use the development branch.

Are you able to add this for iOS too?

**Comment by FSpierckel** [comment]
@TorbenK I'm gonna do it in the dev branch. 
For the iOS version, I already updated the NativePlacesApi.cs file in the iOS project to add the data when the dependency service is called, it's what you're talking about ?

**Comment by TorbenK** [comment]
Oh, somehow I didn't see that. Great!

**Comment by TorbenK** [comment]
Will be in 1.5.1

**Pull request merged**
