### PR TITLE
MapRenderer OnElementChanged signature changed, breaking change

### PR DESCRIPTION
**Pull request by xalikoutis**
#147 So  after upgrading to 2.3.3 nothing was working on the TK map. 
`protected override void OnElementChanged(ElementChangedEventArgs<View> e)` changed to

`protected override void OnElementChanged(ElementChangedEventArgs<Map> e)`
 from MapRenderer

here is the [commit](https://github.com/xamarin/Xamarin.Forms/commit/61f34d113c9f6941194a6ed3101f54158de722a3) from xamarin team that what released with 2.3.3

this PR fixes that

### CODE REVIEW

**Comment by JeanCollas** [comment]
Have you tried it? I did the same on my side, however I can't see pins anymore on Android with the 2.3.3.175 version (I haven't tried on iOS yet)
However the 2.3.3.168  works fine.

**Comment by xalikoutis** [comment]
I tested only with 2.3.3.175 and works as expected. Do a super clean like deleting debug obj, previously all my problems relied on mixed version assemblies. XF and nuget is super for messing up your project and your mind

**Comment by TorbenK** [comment]
Thank you, I merged this manually basically. I will add you as contributor to the readme!

**Comment by xalikoutis** [comment]
Thanks great honor

**Pull request closed without merging**
