### PR TITLE
Fixed null reference exceptions when FormsMap or Map are null

### PR DESCRIPTION
**Pull request by CliffCawley**

### CODE REVIEW

**Comment by TorbenK** [comment]
I really think there is some other root causing these null reference exceptions. For me it looks like you are doing something like binding a collection of pins, then move to another page where the pin collection changes while it is still bound to the map. The problem here is that there is currently nothing which unregisteres the `CollectionChanged` event. So the renderer still listens to the event while the map is actually disposed. 

Normally it should never happen that this events getting raised without a map instance.

**Comment by TorbenK** [comment]
It's also possible that this is the same root causing #36 and #37

**Comment by CliffCawley** [comment]
I think what was happening was I was creating my ViewModel in the constructor and then immediately starting to fill in the pin and route information.

I've since switched to doing this after ViewAppearing has been called.

I'll double check to make sure I'm unbinding when navigating away as well.

**Comment by CliffCawley** [comment]
@TorbenK I think I've determined the cause for some of the null reference crashes.

So basically you ask the map control to calculate the route, it goes off and waits for that to be done. If in the mean time while it's being calculated, the user decides to navigate away from the page (e.g. MainPage = new SomeOtherPage()) then when the route calculation comes in it no longer has a valid control and hence the null reference.

I assume you may need to use Cancellation tokens to cancel any Tasks you start and then cancel them in OnElementChanged override.

You can reproduce it quite easily if you have a page that calculates a route, along with a button that creates a new instance of the same page and assigns it to the app's MainPage, then just spam the button until it crashes.

**Comment by TorbenK** [comment]
Added to dev.

**Pull request closed without merging**
